### PR TITLE
Add DJJob plugin

### PR DESCRIPTION
**Pull request by deizel**

### CODE REVIEW

**Comment by dereuromark** [comment]
The correct plugin name seems to be `CakeDjjob`

**Comment by deizel** [comment]
Your right, I can fix that.. do you prefer [`CakeDjjob`][1] or [`Cake DJJob`][2] as in the readme?

[1]: https://github.com/josegonzalez/cakephp-cake-djjob/blob/master/composer.json#L29
[2]: https://github.com/josegonzalez/cakephp-cake-djjob/blob/master/README.textile#cake-djjob-plugin

**Comment by dereuromark** [comment]
Exactly the plugin name please.

**Comment by deizel** [comment]
Fixed

**Pull request merged**
