### PR TITLE
added Fetchable behavior

### PR DESCRIPTION
**Pull request by segy**
https://github.com/riesenia/cakephp-fetchable

### CODE REVIEW

**Comment by dereuromark** [comment]
Full stop is missing at the end.

As for your plugin:
- missing tests

**Comment by segy** [comment]
thanks... good point. i'll update and let you know

**Comment by segy** [comment]
Hi @ADmad - no problem... I don't force you to use it :) Just pointing out differences - you have `fetchEntity` method available (of course you can add additional one in addition to custom finder to your model, but this means extra writing) plus you have one extra check that even prevents cache engine to be hit. 

As I write in README, it's "Relevant for tables that contain moderate number of rows and are used commonly in many parts of application". I don't say, that this is a common case, but I used it a lot before, so I made it a public package so it can maybe serve someone else.

Btw @dereuromark issues you pointed out are fixed.

**Comment by dereuromark** [comment]
OK
@ADmad shall we merge this?

**Comment by ADmad** [comment]
@segy Since you are using return type hints you should specify the PHP version constraint in your composer.json https://github.com/riesenia/cakephp-fetchable/blob/master/src/Model/Behavior/FetchableBehavior.php#L89

@dereuromark I am fine with merging after the issue I pointed out if fixed. There will probably be others who find this useful :)

**Comment by dereuromark** [comment]
I agree.

**Comment by dereuromark** [comment]
ping @segy Can we proceed here?

**Comment by segy** [comment]
hi. sorry for the delay. i added the php constraint.

**Pull request merged**
