### PR TITLE
added Recaptcha Mailhide plugin

### PR DESCRIPTION
**Pull request by mirko-pagliai**
https://github.com/mirko-pagliai/cakephp-recaptcha-mailhide

### CODE REVIEW

**Comment by mirko-pagliai** [comment]
@dereuromark The suggestion of the VarCI-bot always appears after the pr has been sent. Can not it appear within the form of the pr when you send it?

**Comment by dereuromark** [comment]
No, it cannot. I fixed the missing link for you.

I do have a concern with the license you chose, however.
Is there any specific reason not to go with the recommended MIT license?

> if you provide a service based on software you got under AGPL licensing, you need to provide free access to the complete software for the service

Basically, you prevent anyone from using this plugin in a commercial project - which contradicts a bit the idea of free and universally usable plugins afaik as we list them here.

**Comment by mirko-pagliai** [comment]
I have no problem changing the license of my plugins.
In fact I'm not interested in knowing how they are used.

**Comment by dereuromark** [comment]
Please see https://github.com/FriendsOfCake/awesome-cakephp/blob/master/CONTRIBUTING.md#contribution-guidelines for the recommended license (MIT).

**Comment by mirko-pagliai** [comment]
Okay, I can change the license with MIT. Only one thing though:

> Basically, you prevent anyone from using this plugin in a commercial project - which contradicts a bit the idea of free and universally usable plugins afaik as we list them here.

I do not know where you read this/understand this. Are you sure?
It seems to me that with the AGPL license, you can use the code for commercial purposes. The difference with the GPL license is that if you modify the source, you must release your edit. Or not?

**Comment by dereuromark** [comment]
Yes, we are sure, we discussed that core internally as well.
AGPL is basically one of *the* strictest here.
See wikipedia etc.

Thanks for contributing by the way :)

**Comment by mirko-pagliai** [comment]
Ok ;)

**Comment by mirko-pagliai** [comment]
Done. Now I do it for other plugins as well

**Comment by dereuromark** [comment]
You need to also fix other places, e.g. https://github.com/mirko-pagliai/cakephp-recaptcha-mailhide/blob/master/composer.json#L6 for packagist to display it correctly.
You can also add a badge in the readme as img on the top bar :)

**Comment by mirko-pagliai** [comment]
Done

**Pull request merged**
