### PR TITLE
Add LinkScanner

### PR DESCRIPTION
**Pull request by mirko-pagliai**
Adds https://github.com/mirko-pagliai/cakephp-link-scanner

### CODE REVIEW

**Comment by ADmad** [comment]
Not a good idea suggesting deprecated method `Plugin::load()` in plugin meant for 3.7+.

**Comment by mirko-pagliai** [comment]
> Not a good idea suggesting deprecated method `Plugin::load()` in plugin meant for 3.7+.

it's just a copy-paste in the README that refers to the cookbook. I can obviously delete the example and leave only the reference to the manual.

**Comment by ADmad** [comment]
Best to suggest the CLI command `bin/cake plugin load LinkScanner`.

**Comment by mirko-pagliai** [comment]
Fixed.

**Pull request merged**
