### PR TITLE
Add fertile forest plugin

### PR DESCRIPTION
**Pull request by StewEucen**
@dereuromark 
Changed name. [FertileForest plugin]. Is it right?

https://github.com/StewEucen/fertile-forest-cakephp-plugin

### CODE REVIEW

**Comment by dereuromark** [comment]
Yes, but the description sounds strange yet. Not quite an English sentence.

**Comment by StewEucen** [comment]
@dereuromark 
I updated description like English. How about it?

**Comment by dereuromark** [comment]
Sounds better :)

**Comment by StewEucen** [comment]
Tanks and I am sorry.

**Comment by dereuromark** [comment]
The order is not respected, though. Please read the guidelines of contribution.

**Comment by dereuromark** [comment]
Tests are also missing to show how it works.
Closing for now, please adjust your PR or open a new one.

**Pull request closed without merging**
