### PR TITLE
SweetAlertHelper plugin

### PR DESCRIPTION
**Pull request by falco442**
Added my plugin [sweet-alert-cakephp-3](https://github.com/falco442/sweet-alert-cakephp-3); it allows to use HtmlHelper::link and FormHelper::link with sweet alert 2, a beautiful alert system, alternative to javascript alert

### CODE REVIEW

**Comment by dereuromark** [comment]
You have several issues here:

- composer name does not follow recommendations: cakephp-3- is now a good name here, as the major version should not be reflected - instead `cakephp-sweet-alert-helper` etc would work.
- You dont have any tests
- invalid name, see https://github.com/FriendsOfCake/awesome-cakephp/blob/master/CONTRIBUTING.md

**Comment by dereuromark** [comment]
Also
- https://github.com/falco442/sweet-alert-cakephp/blob/master/src/Controller/AppController.php not needed

You dont seem to use any CS ( https://github.com/falco442/sweet-alert-cakephp/blob/master/src/View/Helper/FormHelper.php )
If you want to use [PSR2R](https://github.com/php-fig-rectified/psr2r-sniffer) (which it seems like), then you must include the sniffer and run it (also in travis). See e.g. my ide-helper plugin on how this is done.
Otherwise you must use sth like the cakephp default one.

**Comment by falco442** [comment]
Thank you! I've never ever used a codesniffer, I installed the CakePHP one. Of course, i let it sniff the code.
I also changed the name of the plugin, removed the AppController that was unnecessary.

But, honestly, I didn't understand what does mean

> Name plugins as ExactPluginName plugin

Can you explain me?

(I still have to change the name of the plugin)

**Comment by dereuromark** [comment]
See the syntax you have in your diff and what the document states?
[sweet-alert-cakephp-3] => [SweetAlertHelper plugin] given the fact that you renamed it to your-vendor-name/cakephp-sweet-alert-helper and the namespace of it is SweetAlertHelper then.

**Comment by dereuromark** [comment]
Yes, but as i mentioned before it makes sense to remove the version number everywhere, especially the github package name.

**Comment by falco442** [comment]
On github, the package name is sweet-alert-cakephp, but packagist doesn't allow me to change the package name; do I have to delete and re-submit the package name to packagist with the new name?

**Comment by dereuromark** [comment]
Your composer require falco442/cakephp-3-sweet-alert-helper is still wrong on the readme afaik
And you dont have any tests yet it seems (only the illusion of it :smile: )

**Pull request closed without merging**
