### PR TITLE
Adds cakebox to software environments

### PR DESCRIPTION
**Pull request by bravo-kernel**
I would appreciate if you would add my cakebox project to the list. I think it's awesome and some (Laravel) users says it kills their Homestead box (and are now using it instead).

If more information is needed there is:

- extensive [documentation here](http://cakebox.readthedocs.org/en/latest/)
- a picture explaining the [architecture](http://cakebox.readthedocs.org/en/latest/quickstart/#box-architecture).

ps: this box does not use chef-provisioning so... no long waiting times, just vagrant up and wait for the Cake3.x console to self-install. After that.. login to the dashboard or start deploying Cake (2.x/3.x) applications, databases, virtual hosts, etc from the commandline using the Cake 3.x Console shells. Supports both public and private repositories too.

TIA

### CODE REVIEW

**Comment by jadb** [comment]
Since it handles cake2 also, why not submit a PR for the master branch as well?

**Comment by bravo-kernel** [comment]
You have a point there Mr. Jadb, if this admission is accepted I will happily do so.

**Comment by dereuromark** [comment]
I would prefer not to merge the cake3 if there was a cake2 PR. There will be merges from 2 to 3. No need to provide it for both in that case :)

**Comment by jadb** [comment]
Oh, noted for next time @dereuromark - I had not realized that. Sorry.

**Comment by bravo-kernel** [comment]
Well, I'm one happy chap now that it's in the 3.x branch. Thanks again :)

**Pull request merged**
