### PR TITLE
does no plural

### PR DESCRIPTION
**Pull request by inoas**

### CODE REVIEW

**Comment by jadb** [comment]
Hmm, need to cater for this use case (fixing existing link) on VarCI's side.

**Comment by inoas** [comment]
I like my new personal overlord.
/me pats @VarCI-bot then bows to it!

**Comment by bravo-kernel** [comment]
@jadb nice bot. 

**HTH:** this is my first acquaintance with the bot and the `Automatic update by Var.CI` message kind of confused me and made me think the bot actually updated something instead of just commenting. Maybe something like `Automatic comment/response by Var.CI` would be more appropriate?

**Comment by jadb** [comment]
@bravo-kernel you are 💯  right!

**Comment by bravo-kernel** [comment]
Probably just about it being a nice bot 😂

**Pull request merged**
