### PR TITLE
Added cakephp-cors plugin under REST and API

### PR DESCRIPTION
**Pull request by LeWestopher**
Thanks for a great CakeFest!

### CODE REVIEW

**Comment by dereuromark** [comment]
Please use the correct name: `Cors plugin`

**Comment by LeWestopher** [comment]
Updated the name.

**Comment by jadb** [comment]
@LeWestopher haven't completely finished checking the plugin, but so far, very nice job!

**Comment by jadb** [comment]
I meant, I haven't yet used it - but love the usage of filters :clap:

**Pull request merged**
