### PR TITLE
MenuLink plugin suggestion added

### PR DESCRIPTION
**Pull request by rrd108**
https://github.com/rrd108/cakephp-menulink

### CODE REVIEW

**Comment by rrd108** [comment]
https://github.com/rrd108/cakephp-menulink

**Comment by dereuromark** [comment]
This one little helper seems rather incomplete to me.
It only supports very basic controller action pairs, what about plugin or prefixes?
What about passed params, or customization?
Not sure this little code snippet here warrants a plugin listing.

**Comment by ADmad** [comment]
Uhm... So this plugin is basically 2 lines of code. IMHO it doesn't provide enough value to warrant being on this list.

**Comment by rrd108** [comment]
Thanks for the feedback, I will add them in the next version. :)

**Pull request closed without merging**
