### PR TITLE
Add AuthManager plugin.

### PR DESCRIPTION
**Pull request by swordbeta**
https://github.com/ExpandOnline/AuthManager

### CODE REVIEW

**Comment by ADmad** [comment]
How would one use this plugin?  The readme should have at least some basic usage instructions.

**Comment by swordbeta** [comment]
@ADmad Added usage documentation.

**Comment by bravo-kernel** [comment]
Entries should be in alphabetical order

**Comment by swordbeta** [comment]
@bravo-kernel Fixed.

**Pull request merged**
