### PR TITLE
Added Airbrake Plugin

### PR DESCRIPTION
**Pull request by chrisShick**
I have decided to created an Airbrake Plugin based around the 2.x version. Let me know if we can get it on the page.

### CODE REVIEW

**Comment by dereuromark** [comment]
Sounds good. You can probably drop the 3 in there, as it is pretty clear those plugins are for 3.x.

**Comment by chrisShick** [comment]
@dereuromark You are right. I just dropped the 3.

**Comment by chrisShick** [comment]
@dereuromark Should I remove the marked out one below it?

**Comment by dereuromark** [comment]
Good catch :) Yeah that would be good.

**Comment by dereuromark** [comment]
And also please respect order (alphab.).

**Comment by chrisShick** [comment]
Order? As in list the airbrake plugin first because it is A?

On Tue, Apr 28, 2015 at 10:37 AM, Mark S. <notifications@github.com> wrote:

> And also please respect order (alphab.).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfCake/awesome-cakephp/pull/92#issuecomment-97109290>
> .
>



-- 
*Chris Hickingbottom*
*Chief Technology Officer*
*Pharmedio
<http://t.signauxsept.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg4WJpLCN1px0zFRYMvbVfD6ll56dMXxf4NtYKd02?t=http%3A%2F%2Fpharmedio.com%2F&si=6147142238339072&pi=ec3fac4f-9f28-4bed-ce49-e3ccad39c461>*
Contact: 601-255-1629

**Comment by dereuromark** [comment]
Yep :)

**Comment by chrisShick** [comment]
Will do :D I'll make another pull request.

**Pull request merged**
