### PR TITLE
Add Settings category and add Settings plugin

### PR DESCRIPTION
**Pull request by bobmulder**

### CODE REVIEW

**Comment by jadb** [comment]
Settings fits better into 'environment' category IMO - am not fond of adding more categories.

**Comment by bobmulder** [comment]
> New categories, or improvements to the existing categorisation are welcome.

@jadb I think the settings plugin is different from plugins listed under `Environment`. Thats why I created a new category. If you really prefer I'll push a new commit so it will be placed under `Environment`.

**Comment by jadb** [comment]
@bobmulder please do - environment is good enough. Not so good standing with just 2 links in there and adding another category with just one link... 

Thanks!

**Comment by bobmulder** [comment]
@jadb Thanks, did it ;)

**Comment by dereuromark** [comment]
The order is not correct yet, it should go above all commented out ones.

**Comment by bobmulder** [comment]
@dereuromark I thought I handled the alphabetic-order-rule right :(

**Comment by dereuromark** [comment]
Thats only for the active ones :P

**Comment by bobmulder** [comment]
Haha I'll remember next time ;) Guess it's okay now?

**Pull request merged**
