### PR TITLE
Add Crud to the REST/API section

### PR DESCRIPTION
**Pull request by bravo-kernel**
Since this might not be evident to (new) users, also promote JSON API a bit more.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
It's only 1 suggestion @VarCI-bot, the other two are whitespace cleaning.

**Comment by dereuromark** [comment]
It is already in CRUD section, please move it here then if that is the better location.

**Comment by bravo-kernel** [comment]
I realize it is in the `skeleton` section already but I feel it deserves to be in two places as it is both a skeleton plugin and an API plugin (IMO). Could an exception for a duplicate entry be tolerated here to better aid the end-user?

**Comment by dereuromark** [comment]
I guess that is reasonable.

**Comment by bravo-kernel** [comment]
Thank you kindly, anybody want to merge this?

**Pull request merged**
