### PR TITLE
Added a TokenVerify Plugin

### PR DESCRIPTION
**Pull request by mosaxiv**
This package provides an Easily issue tokens that can be used for mail authentication.

https://github.com/mosaxiv/cakephp-token-verify

### CODE REVIEW

**Comment by ADmad** [comment]
You should clarity in your readme that the plugin generates JWT :slightly_smiling_face:.

The fact that your a using value of `modified` field to generate signing key concerns me a bit. It means if the record get's edited after JWT is generated the token will never validate.

**Comment by mosaxiv** [comment]
Thanks for review.   Fixed. 😄 

By using modified field, JWT can be used as one-time tokens.  
JWT should be discarded when the table is updated.  
e.g. password reset, email activation, account confirmation.

**Comment by ADmad** [comment]
You should add a clear cautionary note in the readme that the generated JWT will become invalid when user record is updated and then `modified` is updated. Also add an e.g showing how to change the default 10min expiry for the JWT.

**Comment by mosaxiv** [comment]
add usage
https://github.com/mosaxiv/cakephp-token-verify#usage

**Pull request merged**
