### PR TITLE
Added the Jira Plugin.

### PR DESCRIPTION
**Pull request by fr3nch13**
Added the Jira Plugin I wrote under the Third Party APIs section.

https://github.com/fr3nch13/cakephp-jira

### CODE REVIEW

**Comment by dereuromark** [comment]
Your skeleton looks a bit low on files, see other plugins.
Also seems to be missing tests and other requirements as per the howto of this repo.

You could probably use mocks to have tests without having to interact with a real Jira API.

**Comment by fr3nch13** [comment]
I've updated the plugin to include tests and docs. Let me know if I'm missing anything else.

**Comment by fr3nch13** [comment]
Please re-review. I've added more functionality, tests, CI checks and code coverage.

**Comment by dereuromark** [comment]
Tmp should not be committed.

**Comment by fr3nch13** [comment]
That’s where my coverage is getting placed, but touché, I’ll exclude it, and update the CI to create it.

**Pull request merged**
