### PR TITLE
Add icings/partitionable plugin

### PR DESCRIPTION
**Pull request by LordSimal**
Awesome plugin if you need to limit associated data

### CODE REVIEW

**Comment by ADmad** [comment]
@ndm2 Do you approve? :)

**Comment by ndm2** [comment]
I mean... generally, yes, but it's not stable yet.

Based on the feedback so far I don't have any breaking changes planned yet, but that could of course change, and I'm not sure if people would appreciate that from something on this list.

**Comment by ADmad** [comment]
I don't think anyone can complain even if you do make breaking changes following semantic versioning.

**Comment by ndm2** [comment]
If you're OK with it, then please, be my guest :)

image

**Pull request merged**
