### PR TITLE
Added Excel and TableInheritance plugins

### PR DESCRIPTION
**Pull request by robertpustulka**
https://github.com/robotusers/cakephp-excel
https://github.com/robotusers/cakephp-table-inheritance

### CODE REVIEW

**Comment by ADmad** [comment]
@robertpustulka Just out of curiosity have you seen https://github.com/UseMuffin/Sti ?

**Comment by robertpustulka** [comment]
@ADmad yes I have. My approach is a bit different :). And it also supports wildacards so it's great for mapping by mime type (ie. `image/*`).

**Comment by ADmad** [comment]
@robertpustulka Okay :)

**Comment by ADmad** [comment]
Having a badge for codecoverage in the readme of plugins would be nice.

**Comment by robertpustulka** [comment]
@ADmad done

**Pull request merged**
