### PR TITLE
add another asset manager

### PR DESCRIPTION
**Pull request by visonforcoding**
combine and compress asset ,output html with develop and production mode

### CODE REVIEW

**Comment by ADmad** [comment]
What does  this plugin provide that already listed plugins like AssetCompress don't?

**Comment by visonforcoding** [comment]
@ADmad  yes, like AssetCompress . just I think mine is easier to use.

**Comment by ADmad** [comment]
How is it easier yo use?

**Comment by dereuromark** [comment]
Closing as this got stale. 
Please try to see if you can instead contribute to the de facto standard plugin AssetCompress, providing your improvements there. Thanks a lot for your contribution.

**Pull request closed without merging**
