### PR TITLE
Curation as per #152

### PR DESCRIPTION
**Pull request by bravo-kernel**
- removes not-upgraded plugins (moved to wiki)
- adds plugins that have been upgraded since
- fixed ordering
- renames CakePHP Books category to "CakePHP Books and Articles"
- cleans up header

Todo::

- category sorting (separate PR)
- rewrite/remove plugins.cakephp.org description

### CODE REVIEW

**Comment by bravo-kernel** [comment]
wtf, I see stuff removed for sure :open_mouth:

**Comment by bravo-kernel** [comment]
Added Table of Contents

**Comment by bravo-kernel** [comment]
Header rewritten to be more compact and readable. Good to merge if you ask me.

**Comment by dereuromark** [comment]
:+1:

**Pull request merged**
