### PR TITLE
Adding LDAP, CakeSoap, and CakeSpreadsheet

### PR DESCRIPTION
**Pull request by darensipes**
- https://github.com/QueenCityCodeFactory/LDAP
- https://github.com/QueenCityCodeFactory/CakeSoap
- https://github.com/QueenCityCodeFactory/CakeSpreadsheet

### CODE REVIEW

**Comment by dereuromark** [comment]
Are you sure the plugin names are as they are in code?

**Comment by ADmad** [comment]
None of your plugins have tests.

**Comment by darensipes** [comment]
@dereuromark Not sure what you are asking? They are named the same from what I can tell.

@ADmad Correct, we have no tests for these plugins currently. We could add them. Do we need the tests for them to be added to the list? Tests are something I could use help with, to be honest. I have minimal experience writing tests.

**Comment by dereuromark** [comment]
https://github.com/QueenCityCodeFactory/LDAP/blob/master/composer.json#L33
is the correct plugin name. Please respect casing.
Also install docs should be complete etc.

**Comment by dereuromark** [comment]
License files are missing! As per Guidelines.

**Comment by ADmad** [comment]
Reasonable amount of time has passed and still no tests have been added to the linked plugins, hence closing the PR.

**Pull request closed without merging**
