### PR TITLE
Remove Blame as it has been marked abondoned

### PR DESCRIPTION
**Pull request by ADmad**
https://packagist.org/packages/ceeram/cakephp-blame

### CODE REVIEW

**Comment by Oxicode** [comment]
Why. Sí funciona

**Comment by ADmad** [comment]
@Oxicode You should ask that to the plugin author :)

**Comment by dereuromark** [comment]
Well, thats bad because other plugins have been rejected and not been added to the list in favor of Blame.
Any alternatives?

**Comment by ADmad** [comment]
The suggested alternative muffin/footprint is already one the list :)

**Pull request merged**
