### PR TITLE
Updated opauth plugin

### PR DESCRIPTION
**Pull request by wouter0100**
For CakePHP 3

### CODE REVIEW

**Comment by dereuromark** [comment]
I am fine with this as the original repo owner hasn't migrated his code to Cake3 yet.
So no need to keep the strike though 2.x version when there is a 3.x version.
Once the original owner upgraded, we can add this one as well then.

**Comment by wouter0100** [comment]
Ah, great! Unfortunantly, the creators of opauth seems to be inactive. That's the main reason why I didn't create a pull-request instead of a "new" repo.

Thanks.

**Comment by dereuromark** [comment]
Refs https://github.com/uzyn/cakephp-opauth/issues/46

**Comment by jadb** [comment]
Why have you deleted the repo without notifying us?

**Pull request merged**
