### PR TITLE
Add DataSeed plugin

### PR DESCRIPTION
**Pull request by andrej-griniuk**
https://github.com/andrej-griniuk/cakephp-data-seed

### CODE REVIEW

**Comment by jadb** [comment]
So is this a select with limit to create the data seed? If that's the only functionality, wouldn't this have been much better contributed back to the migrations plugin?

If so, like its counterpart (fixture generation from database records) should be part of the core IMO.

**Comment by jadb** [comment]
That doesn't mean I don't like the plugin! To the contrary, it just means I find its so important that it should be part of core. 

So thanks @andrej-griniuk!

**Comment by andrej-griniuk** [comment]
Thank @jadb! Yep, that's pretty much all it does.

https://github.com/cakephp/migrations/issues/191
I saw this discussion and thought that quite a bit more is expected from this kind of feature. However I do believe that there is plenty of users like myself who only need as much as I've implemented here. So if you guys think that's good enough I'm more than happy to make a pull request to the migrations plugin instead.

**Comment by dereuromark** [comment]
Lets try the pr for Migrations. If that's works awesome :) everyone uses that already anyway.

**Comment by andrej-griniuk** [comment]
https://github.com/cakephp/migrations/pull/260

**Pull request closed without merging**
