### PR TITLE
Ratchet is being upgraded to cake3

### PR DESCRIPTION
**Pull request by WyriHaximus**
https://github.com/WyriHaximus/Ratchet
Started work on upgrading this and related plugins

/cc #121

### CODE REVIEW

**Comment by dereuromark** [comment]
Sure the alphabetic order is correct? 
Note that commented out ones don't count.

**Comment by WyriHaximus** [comment]
Yeah the order is correct, it is the only one not commented out.

Travis is being worked on together with the rest of the plugin, want me to ping you once it has been resolved before you merge?

**Comment by dereuromark** [comment]
I didnt see that you removed the other ones.
Well, all right.

**Comment by jadb** [comment]
@WyriHaximus he meant you should move it above the ones that are commented out.

Please, ping when the plugin is ready for alpha at the very least so people don't use it pre-emptively.

**Comment by WyriHaximus** [comment]
@jadb aah doh, done :).

Will ping when it's alpha

**Pull request merged**
