### PR TITLE
Added CipherBehavior plugin

### PR DESCRIPTION
**Pull request by adayth**
Plugin link here: https://github.com/adayth/cakephp-cipher-behavior

This is functionality that I developed for a company project. Is tested and published in packagist.

I hope you consider it useful to add to the list.

### CODE REVIEW

**Comment by dereuromark** [comment]
It would be great to have travis CI testing enabled on it.
Other than that it looks good!

PS: On a personal note I would have probably used the generic name `Cipher` (without the Behavior suffix) for the plugin name, as the behavior is a specific pattern and this plugin might be some day more than only a behavior, maybe also a lib or shell or whatever :) So you are restricting yourself here maybe a little bit.

**Comment by adayth** [comment]
I'll try to add CI testing soon. I need to search how to do it properly. Any ideas or suggestions are welcome.

I understand your point of view on the name, but I prefer to keep Cipher free for a more generic library that anyone could develop. This plugin is intended to be a behavior and nothing else. I think that is more clear to know that a project is only a behavior just by reading its name.

Thank you for the feedback ;)

**Comment by dereuromark** [comment]
Look how other plugins do it. But you basically just have to put the travis file in and enable the github hook for it.

**Comment by dereuromark** [comment]
Looks like a few builts are failing yet: https://travis-ci.org/adayth/cakephp-cipher-behavior

**Comment by adayth** [comment]
Tests are passing right now. Thank you for your help.

P.S.: maybe this is not the right place, but you can point me to any resources about Readme icons to show status of: coveralls, travis and other info.

**Comment by dereuromark** [comment]
Just check the existing plugins (mine for example). There are tons of examples.

**Comment by dereuromark** [comment]
As for the table schema, you can look into creating a plugin migration using the cakephp/migrations plugin.

**Comment by adayth** [comment]
Thanks @dereuromark ! The schema is just an example to show a common use case and binary column use.

**Comment by dereuromark** [comment]
Ah ok ;)

**Pull request merged**
