### PR TITLE
CORS plugin for API

### PR DESCRIPTION
**Pull request by ozee31**
https://github.com/ozee31/cakephp-cors

### CODE REVIEW

**Comment by dereuromark** [comment]
Tests seem missing here.

**Comment by dereuromark** [comment]
Same question here:
What does your plugin improve or add on top of the existing https://github.com/snelg/cakephp-cors one?
Just wondering why not joining forces instead of duplicating the efforts maybe?

**Comment by ozee31** [comment]
My plugin use Middleware while snelg/cakephp-cors use Filters (it's deprecated) in Cake 3.3

**Comment by dereuromark** [comment]
Fair enough then :+1: 

PS: But you could have still contributed those improvements into the original repo as PR to keep it a single and "de facto standard" plugin. This should be the preferred thing over forking, or parallel dev.

**Comment by ozee31** [comment]
I had not seen this plugin before it. I did not find on Google and I did not know the repo awesome

**Comment by dereuromark** [comment]
You can still ask the other maintainer if he wants your improvements, or you could PR them (deprecating the old way there).
This way you can still work together, if you two want to.

**Comment by ozee31** [comment]
I tried to contact him but his approach is different, my configuration is global and her own in every routes.

**Comment by ozee31** [comment]
The snelg's plugin is unmaintained, you can replace it with my plugin.

See discussion: 
[https://github.com/snelg/cakephp-cors/issues/13#issuecomment-259487416](https://github.com/snelg/cakephp-cors/issues/13#issuecomment-259487416)

**Comment by dereuromark** [comment]
All right. Please don't forget to add test coverage and all the quality tooling the current plugins on this list have.

**Comment by ozee31** [comment]
yes, I will write the tests soon

**Comment by ozee31** [comment]
Hi, I added unit tests and I also activated travis.

**Comment by bravo-kernel** [comment]
Good job mr. @ozee31 👍, LGTM

**Pull request merged**
