### PR TITLE
AssetCompressImproved plugin and JadeView plugin

### PR DESCRIPTION
**Pull request by clthck**
Add 2 new plugins to the list

### CODE REVIEW

**Comment by dereuromark** [comment]
Ideally, each addition is an own PR.
Now the one plugin cannot be added because of discussion about the other (new) one.

Why do you need to hard-fork the AssetCompress one?
Wasn't it possible to PR the functionality? As this is an activiely maintained (de facto standard) plugin.

**Comment by clthck** [comment]
I tried to suggest my fix with a pull request, but @markstory didn't want to accept my update. So I decided to make a new one.

**Comment by clthck** [comment]
You can check our conversations [here](https://github.com/markstory/mini-asset/pull/18)

**Comment by jadb** [comment]
I would split this PR in 2.

Also, I would not add a new AssetCompress plugin and mix-up the community about which to use when it only adds a feature for a limited scope of use cases. 

Instead, I suggest we link to it next to AssetCompress and update its README to point to the PR and/or describe what it adds to the original one so people can decide at a glance what to use. 

After all, and unless you keep rebasing from @markstory's plugin (which is the official one we promote to people), users will run into problems - so better they know what advantages they are getting by using it and judge if they want to or not.

**Pull request closed without merging**
