### PR TITLE
CakePHP Vagrant Setup

### PR DESCRIPTION
**Pull request by cpierce**
Added https://github.com/cpierce/cakephp-vagrant-setup to environment setups. This allows users to spin up a vanilla Cake PHP 3.x environment and immediately start the development process.

### CODE REVIEW

**Comment by ionas** [comment]
I am using puphpet for this - https://gist.github.com/ionas/d45e44b9576fdc9f2f02c3c25dfa3501 - however I really like your approach because it is little magic - and more options (esp to learn from) = great.

p.s.: do you setup databases to be my_app:my_app:secret by default?

**Comment by cpierce** [comment]
@ionas - i set up the database to be dev:root:'' by default.  Would that be the preferred?

**Comment by jhli** [comment]
I'd try to set it to defaults that match composer create-project cakephp/app

**Comment by cpierce** [comment]
this now matches the create project defaults and runs on ubuntu 16.04 LTS with PHP 7 and mysql 5.7

**Comment by cpierce** [comment]
Ping!

**Pull request merged**
