### PR TITLE
Mark FractalTransformerView plugin as CakePHP 4 compatible

### PR DESCRIPTION
**Pull request by andrej-griniuk**
https://github.com/andrej-griniuk/cakephp-fractal-transformer-view

### CODE REVIEW

**Comment by ADmad** [comment]
The plugin's readme still shows use of special view variables like `_serialize` (which have been deprecated in 4.x) instead of ViewBuilder options.

**Comment by andrej-griniuk** [comment]
> The plugin's readme still shows use of special view variables like `_serialize` (which have been deprecated in 4.x) instead of ViewBuilder options.

Oooops. Will sort it out

**Comment by andrej-griniuk** [comment]
Done!

**Comment by ADmad** [comment]
Your readme example shows setting of paginated articles but I don't see CakePHP specific [paginator adapter](https://fractal.thephpleague.com/pagination/) in the plugin, so your output won't contain any pagination data.

**Pull request merged**
