### PR TITLE
Add CakePHP-Upload 3.x

### PR DESCRIPTION
**Pull request by davidyell**
Now that @savant has done a release, I think we can include this as an option

### CODE REVIEW

**Comment by dereuromark** [comment]
Space instead of `-`.

**Comment by davidyell** [comment]
That is the name of the plugin.

**Comment by dereuromark** [comment]
According to their docs (`Plugin::load('Josegonzale/Upload');`) the name is  `'Josegonzale/Upload'`.

**Comment by dereuromark** [comment]
I rather trust composer, though: `Josegonzalez/Upload`

**Comment by dereuromark** [comment]
?

**Pull request closed without merging**
