### PR TITLE
Add webservices plugin

### PR DESCRIPTION
**Pull request by Marlinc**
I've added the https://github.com/usemuffin/webservice plugin which now contains a ORM like interface to work with webservices. I'm not sure if this it the right section, if not this can me moved to another section.

### CODE REVIEW

**Comment by dereuromark** [comment]
Fullstop missing at the end.
But looks good.

**Comment by Marlinc** [comment]
There you go!

**Comment by bravo-kernel** [comment]
`An ORM like interface` instead of `A ORM like interface` IMHO

**Comment by Marlinc** [comment]
Good one, it has been changed. I've squashed the commits as well.

**Pull request merged**
