### PR TITLE
Add DatabaseLog

### PR DESCRIPTION
**Pull request by dereuromark**
https://github.com/dereuromark/CakePHP-DatabaseLog

### CODE REVIEW

**Comment by jippi** [comment]
LGTM; though the README lacks a huge warning that it very quickly can go out of hand performance and size wise logging to a database. 

Having a (semi)automated way to rotate logs when number of rows/table size exceed $x or simply by date range (e.g. auto-delete rows older than $x days with a gc probability / shell to do it)

**Comment by inoas** [comment]
This is great stuff.

**Comment by dereuromark** [comment]
Added note in https://github.com/dereuromark/CakePHP-DatabaseLog/blob/master/README.md#log-rotation

**Comment by dereuromark** [comment]
The next minor will also natively contain a few shell commands for garbage collect and alike.

**Pull request merged**
