### PR TITLE
Use awesome_bot for link validation.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
Cool :)

**Comment by dereuromark** [comment]
CommonMark plugin can be removed from the Markup section. 
I wonder if we should remove that section alltogether and move the Geshi one to Templating section.

**Comment by dereuromark** [comment]
Can we --allow-dupe for now?

**Comment by dereuromark** [comment]
404 http://www.meetup.com/nyc-cakephp/ other than that it looks good.

**Comment by ADmad** [comment]
http://www.meetup.com/nyc-cakephp/  is accessible for me.

**Comment by ADmad** [comment]
Silly me it's a 404 page.

**Comment by ADmad** [comment]
Victory!

**Comment by dereuromark** [comment]
What do you think about removing the Markup section in favor of Templating?

**Comment by josegonzalez** [comment]
Do it.

**Comment by josegonzalez** [comment]
@dereuromark I think the guy who "owned" it ended up not renewing?

**Pull request merged**
