### PR TITLE
Adds inertia.js adapter

### PR DESCRIPTION
**Pull request by ishanvyas22**
Adds https://github.com/ishanvyas22/cakephp-inertiajs

### CODE REVIEW

**Comment by dereuromark** [comment]
- Invalid name, please see guidelines.
- no tests

as for your naming: InertiaCake is confusing when the package name is ishanvyas22/inertia-cakephp maybe.
Most prefix it here with Cake instead of suffix: CakeInertia
But not a big deal.

**Comment by dereuromark** [comment]
ping @segy Can we proceed here?

**Comment by ishanvyas22** [comment]
Yes

**Comment by dereuromark** [comment]
I dont see any of the first two critical points adressed, though.
Closing then for now. It requires a fresh PR with all the guidelines addressed.

**Pull request closed without merging**
