### PR TITLE
https://github.com/cpierce/cakephp-vagrant-setup added to Environments section.

### PR DESCRIPTION
**Pull request by cpierce**
Added https://github.com/cpierce/cakephp-vagrant-setup to environment setups.

### CODE REVIEW

**Comment by bravo-kernel** [comment]
Could you explain what the specific benefits for CakePHP users would be when using this deployment?

**Comment by cpierce** [comment]
on this PR or in the actual data submitted in the PR? @bravo-kernel

**Comment by dereuromark** [comment]
also needs rebasing.

**Comment by bravo-kernel** [comment]
@cpierce I asked in the context of the repository because it looked like a plain vagrant to me without added value for Cake users. On the other hand, being plain can be a good thing by itself ;) Please don't take offense.

**Comment by cpierce** [comment]
No I don't, just mine spins up a cakephp setup as a default.

On Wed, May 25, 2016 at 3:09 PM, bravo-kernel <notifications@github.com>
wrote:

> @cpierce <https://github.com/cpierce> I asked in the context of the
> repository because it looked like a plain vagrant to me without added value
> for Cake users. On the other hand, being plain can be a good thing by
> itself ;) Please don't take offense.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfCake/awesome-cakephp/pull/202#issuecomment-221675927>
>



-- 
*Chris Pierce*


PO Box 536, Durant OK 74702-0536

**Comment by bravo-kernel** [comment]
Do you mean it automatically sets up a virgin cakephp application, perhaps even using [this role](https://github.com/cpierce/cakephp-vagrant-setup/blob/43f93f26ae547080456535d4a5fa412213c28df7/roles/cake/tasks/main.yml)? If so, that would be a nice thing and maybe something to be added to the readme, it wasn't clear to me.

**Comment by cpierce** [comment]
Yes it does.  I will make the readme more clear.

On Wed, May 25, 2016 at 3:19 PM, bravo-kernel <notifications@github.com>
wrote:

> Do you mean it automatically sets up a virgin cakephp application, perhaps
> even using this role
> <https://github.com/cpierce/cakephp-vagrant-setup/blob/43f93f26ae547080456535d4a5fa412213c28df7/roles/cake/tasks/main.yml>?
> If so, that would be a nice thing and maybe something to be added to the
> readme, it wasn't clear to me.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfCake/awesome-cakephp/pull/202#issuecomment-221678679>
>



-- 
*Chris Pierce*


PO Box 536, Durant OK 74702-0536

**Comment by bravo-kernel** [comment]
👍🏼

Sent from my Mobile Device

**Comment by cpierce** [comment]
@dereuromark - what needs rebasing?

**Comment by dereuromark** [comment]
This PR. it is currently conflicting.

**Pull request closed without merging**
