### PR TITLE
Added Salesforce Plugin

### PR DESCRIPTION
**Pull request by voycey**
Mark - I changed the repo to your specs in previous PR, now contains both 2.x and 3.x branches and renamed

### CODE REVIEW

**Comment by dakota** [comment]
I'm getting a 404 when I try to visit the plugin url

**Comment by jippi** [comment]
ditto

**Comment by voycey** [comment]
Gah sorry - see latest

**Comment by dereuromark** [comment]
Looks good but you need to rebase.

**Comment by voycey** [comment]
Done :)

**Comment by dereuromark** [comment]
Nah, still not mergeable, I think you are not rebasing on top of current origin master.

**Comment by dereuromark** [comment]
Resolved with https://github.com/FriendsOfCake/awesome-cakephp/commit/f707fcb97a0da9b58ba88690dc01a9e676f6c485
Thank you!

**Pull request closed without merging**
