### PR TITLE
Added `Monga` plugin for accessing MongoDB with PHP League's Monga library

### PR DESCRIPTION
**Pull request by LeWestopher**
https://github.com/lewestopher/cakephp-monga

### CODE REVIEW

**Comment by dereuromark** [comment]
travis testing would be nice
And your badges (the links) are broken.

**Comment by LeWestopher** [comment]
Fixing badge buttons immediately, then Travis integration shortly after that.  Will report back when finished.  Thanks for the heads up on the buttons :)

**Comment by LeWestopher** [comment]
Mark,

Badge links fixed.  Added Travis + Coveralls per your request.

**Comment by ADmad** [comment]
Strange, why does packagist show only 1 install https://packagist.org/packages/lewestopher/cakephp-monga ?

Just a single travis build would cause 4-5 installs.

**Comment by dereuromark** [comment]
You should probably add 7.0 to the travis matrix.
But looks good to me!
Thanks for you contribution on the no sql front :)

**Comment by LeWestopher** [comment]
ADmad, I had wondered the same thing.  Do you have any insight as to why the download link might not be incrementing?

**Comment by ADmad** [comment]
@LeWestopher No idea

**Pull request merged**
