### PR TITLE
MixerApi/ExceptionRender

### PR DESCRIPTION
**Pull request by cnizzardini**
https://github.com/mixerapi/exception-render

### CODE REVIEW

**Comment by dereuromark** [comment]
Those are a lot of very specific, edge case plugins it seems
I wonder if it was better to just list the main one?
Or what's the use case for these small specific ones as standalone usage?

**Comment by ADmad** [comment]
Yeah I too don't see someone using this plugin standalone.

**Comment by cnizzardini** [comment]
I can close this one.

**Comment by cnizzardini** [comment]
> Those are a lot of very specific, edge case plugins it seems
> I wonder if it was better to just list the main one?
> Or what's the use case for these small specific ones as standalone usage?

It's modular components. So it's up to the developer to decide what they need.

**Pull request closed without merging**
