### PR TITLE
Add Galley Plugin

### PR DESCRIPTION
**Pull request by amayer5125**
Galley is a command line utility used to control a small docker environment. It includes bin/cake integration to set up the docker environment on existing applications.

### CODE REVIEW

**Comment by cnizzardini** [comment]
Hey @amayer5125 this is pretty neat. I might want to help out on this. Have you looked at this at all: https://github.com/cnizzardini/cakephp-docker

It does a lot of that stuff, but with a Makefile, in particular it would be cool to see the xdebug toggle integrated into galley. Also the ability to swap out Dockerfiles with userland ones.

**Comment by amayer5125** [comment]
@cnizzardini thanks for your interest! I believe both of your concerns are already solved in Galley.

xdebug can be toggled by adding an environment variable to docker-compose.yml like this:

```yaml
services:
  app:
    environment:
      XDEBUG_MODE: "off"
```

Users can publish the Galley docker files to their repo using `bin/cake galley publish`. This allows them to modify the Galley docker files and rebuild their images. Users can also replace the `build` and `image` config in docker-compose.yml to use any docker image they like.

**Comment by cnizzardini** [comment]
> @cnizzardini thanks for your interest! I believe both of your concerns are already solved in Galley.
> 
> xdebug can be toggled by adding an environment variable to docker-compose.yml like this:
> 
> ```yaml
> services:
>   app:
>     environment:
>       XDEBUG_MODE: "off"
> ```
> 
> Users can publish the Galley docker files to their repo using `bin/cake galley publish`. This allows them to modify the Galley docker files and rebuild their images. Users can also replace the `build` and `image` config in docker-compose.yml to use any docker image they like.

Yeah but you can simplify for the user's sake by modifying the compose file via sed or whatever, then triggering a restart of the php container.

**Comment by amayer5125** [comment]
Do users enable/disable xdebug that often? I could see the use case where a user doesn't want XDebug at all will disable it, but I don't believe I've seen people turn it on and off throughout the day. I could be in the minority here though.

**Pull request merged**
