### PR TITLE
Add Rest plugin

### PR DESCRIPTION
**Pull request by narendravaghela**
https://github.com/sprintcube/cakephp-rest

### CODE REVIEW

**Comment by davidyell** [comment]
I can't see anything in this plugin which cannot be achieved in the core already.

**Comment by narendravaghela** [comment]
Just updated the repository URL - https://github.com/sprintcube/cakephp-rest

**Comment by dereuromark** [comment]
@ADmad What shall we do here?

**Comment by ADmad** [comment]
- Seeing things like `RestController` is quite off putting to me. The lone `beforeRender()` in the controller could go in a component instead. 
- The use of .ctp files for returning JSON in spite of using a custom JsonView seems quite unnecessary.

I am not comfortable promoting such practices.

**Comment by dereuromark** [comment]
All right, let's close this for a revised and possible future contribution for 4.x then.

**Pull request closed without merging**
