### PR TITLE
Adding Middleware Section

### PR DESCRIPTION
**Pull request by chrisShick**
Now that CakePHP is supporting Middleware, I feel that a middleware section is needed. I have also submitted my new [CakeMiddlewares](https://github.com/chrisShick/CakeMiddlewares) repo to start it off.

### CODE REVIEW

**Comment by chrisShick** [comment]
I am not too sure why Travis failed

**Comment by ADmad** [comment]
I don't think are going to be many plugins with a bunch of middleware for various purposes to warrant a separate category.

**Comment by chrisShick** [comment]
Oh, I did not mean it just for plugins that have middleware for various purposes. I just meant that, with MIddleware being such a new thing for Cake, it might be useful to have a section dedicated to that for quick reference.

**Comment by chrisShick** [comment]
Would y'all prefer me to add it under miscellaneous?

**Comment by ADmad** [comment]
> Would y'all prefer me to add it under miscellaneous?

Yes please.

**Comment by chrisShick** [comment]
@ADmad Alright, miscellaneous it is!

**Comment by chrisShick** [comment]
What do I need to do to fix this travis failure?

**Comment by dereuromark** [comment]
Someone just needs to fix that vagrant thing link. Not related to your changes :)

**Comment by dereuromark** [comment]
As a side note:
Those middleware might be better suited inside specific plugins for each "topic".
E.g. the geo one would better be found and expected inside my [Geo](https://github.com/dereuromark/cakephp-geo) plugin.
For security related things, a "cakephp-security" plugin could make sense.
Having a generic catch-all one means it basically hides all the features under a too generic name.
It also violates the package principle, where things belonging to each other are best put together - as otherwise the reason to change for one trickles down on the others.

**Pull request merged**
